melonStore/project/melons/views.py
from flask import Blueprint, render_template, redirect, url_for, session, request, flash
from project.models import melon_list, Melon
from project.melons.forms import AddForm
from pprint import pprint

melons_blueprint = Blueprint('melons', __name__,template_folder='templates/melons')

@melons_blueprint.route('/all_melons')
def all_melons():

    melons = melon_list()
    for melon in melons:
        session[melon.melon_id] = melon.to_dict()
    
    return render_template('all_melons.html', melons=melons)


@melons_blueprint.route('/melon_details/<melon_id>', methods=["GET", "POST"])
def melon_details(melon_id):
    print(f'melon id {melon_id}') 
    session_melon = session.get(str(melon_id), {})
    print(f"session melon before dictionary {session_melon}")
    melon = Melon.from_dict(session_melon)


    print(f'just melon {melon}') 
    print(f"session melon {session_melon}")
    print(f"session cart {session['cart']}")
    form = AddForm()

    if request.method == "POST":
        if form.validate_on_submit():
            print("Validation is successful.")
            
            melon_update = None

            if 'cart' not in session:
                session['cart'] = []
                print('cart initialized empty list')

            print(session['cart'])

            for mel in session['cart']:
                print(f"mel for mel in cart {mel}")
                if mel['melon_id'] == melon_id:
                    mel['quantity'] += int(form.quantity.data)
                    mel['subtotal'] = mel['price'] * mel['quantity']
                    print(f'melon in session{mel}') 
                    melon_update = mel
                    print(f'melon update {melon_update}')
                    session.modified = True
                    flash(f'{melon.common_name} has been updated!')
                    break 

            if melon_update is None:
                new_melon = Melon.to_dict(melon)
                new_melon['quantity'] = int(form.quantity.data)
                new_melon['subtotal'] = new_melon['price'] * new_melon['quantity']
                print(f'melon {new_melon}') 
                session['cart'].append(new_melon)
                session.modified = True
                flash(f'{melon.common_name} has been added to cart!')
                print(f"session cart {session['cart']}")   
            return redirect(url_for('cart.view_cart'))
        
    return render_template('melon_details.html', melon=melon, form=form)

melonStore/project/users/views.py
from flask import Blueprint, render_template, redirect, request, url_for, flash , session
from project.models import User, get_by_username, customers
from project.users.forms import LoginForm,RegistrationForm
from flask_login import login_user, login_required, logout_user
from flask_bcrypt import Bcrypt

bcrypt = Bcrypt()

users_blueprint = Blueprint('users', __name__, template_folder='templates/users')

@users_blueprint.route('/welcome')
@login_required
def welcome_user():
    return render_template('welcome_user.html')

@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    del session["username"]
    flash('You logged out!')
    return redirect(url_for('home'))

@users_blueprint.route('/login', methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        user = get_by_username(form.username.data)
        print(f'get user {user}')
        if user is not None:
            print(user.password_hash)
            if user.check_password(form.password.data):
                login_user(user)
                session["username"] = user.username
                flash('Logged in Successfully!')

                next = request.args.get('next')

                if next == None or not next[0] == '/':
                    next = url_for('users.welcome_user')

                return redirect(next)
    
    return render_template('login.html', form=form)

@users_blueprint.route('/register', methods = ['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():

        RegistrationForm.check_username(form.username.data)
        password_hash = bcrypt.generate_password_hash(form.password.data)
        user = User(username = form.username.data,
                    password_hash = password_hash,
                    name = form.name.data)
        
        customers[user.username] = user.to_dict()
        print(user.password_hash)
        flash('Thanks for registration!')
        return redirect(url_for('users.login'))
    
    return render_template('register.html', form=form)

melonStore/project/templates/base.html
<html>
<head>
    <title>Shopping Site</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
        <div class="container-fluid">
            <ul class="navbar-nav mr-auto">
                <a class="navbar-brand" href="#">Ubermelon</a>
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{{url_for('home')}}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{{url_for('melons.all_melons')}}">All Melons</a>
                </li>
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{{url_for('cart.view_cart')}}">View Cart</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{{url_for('users.logout')}}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{{url_for('users.login')}}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a>
                </li>
                {% endif %}
            </ul>

            <div class="collapse navbar-collapse">
                <div class="navbar-nav">
                </div>
            </div>
        </div>
    </nav>

  <div class="container">
    {% block content %}
        
    {% endblock %}

  </div>

</body>
</html>

melonStore/project/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
    <h1>Welcome to our Melon Shop!</h1>
    {% if current_user.is_authenticated %}
    <p>Hi {{current_user.username}}!</p>
    {% else %}
    <p>Please login or register</p>
    {% endif %}
    <img class="container mx-auto" src="http://tinyurl.com/nhzxvvx7" alt="Melon Shop Image">
</div>
{% endblock %}