melonStore/project/cart/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, IntegerField

class EditForm(FlaskForm):

    quantity = IntegerField('Quantity: ')
    submit = SubmitField('Update')

melonStore/project/cart/views.py
from flask import Blueprint, render_template, redirect, url_for, session, request
from project.cart.forms import EditForm



cart_blueprint = Blueprint('cart', __name__,template_folder='templates/cart')

@cart_blueprint.route('/view_cart')
def view_cart():
    if 'username' not in session:
        return redirect(url_for('users.login'))
    
    melon_list = []
    order_total = 0.00
    for melons in session['cart']:
        print(f'melons in session cart {melons}')
        melon_list.append(melons)
        melons['subtotal'] = melons['quantity'] * melons['price']
        order_total += melons['subtotal']

    print(f'melon list {melon_list}')

    return render_template('cart.html', melon_list=melon_list, order_total=order_total, form=EditForm())

@cart_blueprint.route("/empty-cart")
def empty_cart():
   session['cart'] = []
   print(session['cart'])
   return redirect(url_for('cart.view_cart'))

@cart_blueprint.route('/edit_cart/<melon_id>', methods=['GET', 'POST'])
def edit_cart(melon_id):

    form = EditForm()

    if request.method == "POST":
        if form.validate_on_submit():
            print("Validation is successful.")

            for mel in session['cart']:
                if mel['melon_id'] == melon_id:
                    mel['quantity'] = int(form.quantity.data)
                    mel['subtotal'] = mel['price'] * mel['quantity']
                    session.modified = True
            return redirect(url_for('cart.view_cart'))
    return render_template('view_cart.html', form=form, melon_id=melon_id)

melonStore/project/cart/templates/cart/cart.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron container-fluid row flex" >
        <h1>Cart</h1>
        <div class="col-md-2 mb-4">
            <a href="{{ url_for('cart.empty_cart') }}" class="btn btn-primary">Empty Cart</a>
        </div>
        <div class="row">
            {% for melon in melon_list %}
                <div class="col-md-2 mb-4">
                    <a href="{{ url_for('melons.melon_details', melon_id=melon.melon_id) }}">        
                        <img src="{{ melon.image_url }}" alt="{{ melon.common_name }}" class="rounded galleryImg" >
                    </a>
                    <br>
                    {{ melon['common_name'] }} <br>
                    <p>Price: ${{ melon['price'] }}</p>
                        <form method="POST" action="{{ url_for('cart.edit_cart', melon_id=melon.melon_id) }}">
                            {{ form.hidden_tag() }}
                            Subtotal({% if melon['quantity'] > 1 %}
                                items
                                {% else %}
                                item
                                {% endif %}) : ${{ '%.2f'|format(melon['subtotal']) }}
                                {{form.quantity(value=melon.quantity)}}
                                
                            <br>
                            {{form.submit()}}
                        </form>
                        </div>
            {% endfor %}
        </div>
        <p>Total: ${{ '%.2f'|format(order_total) }}</p>
    </div>
{% endblock %}