melonStore/project/melons/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, IntegerField

class AddForm(FlaskForm):

    quantity = IntegerField('Quantity: ')
    submit = SubmitField('Add to Cart')

melonStore/project/melons/views.py
from flask import Blueprint, render_template, redirect, url_for, session, request, flash
from project.models import melon_list, Melon
from project.melons.forms import AddForm
from pprint import pprint

melons_blueprint = Blueprint('melons', __name__,template_folder='templates/melons')

@melons_blueprint.route('/all_melons')
def all_melons():

    melons = melon_list()
    for melon in melons:
        session[melon.melon_id] = melon.to_dict()
    
    return render_template('all_melons.html', melons=melons)


@melons_blueprint.route('/melon_details/<melon_id>', methods=["GET", "POST"])
def melon_details(melon_id):
    print(f'melon id {melon_id}') 
    session_melon = session.get(str(melon_id), {})
    print(f"session melon before dictionary {session_melon}")
    melon = Melon.from_dict(session_melon)


    print(f'just melon {melon}') 
    print(f"session melon {session_melon}")
    print(f"session cart {session['cart']}")
    form = AddForm()

    if request.method == "POST":
        if form.validate_on_submit():
            print("Validation is successful.")
            
            melon_update = None

            if 'cart' not in session:
                session['cart'] = []
                print('cart initialized empty list')

            print(session['cart'])

            for mel in session['cart']:
                print(f"mel for mel in cart {mel}")
                if mel['melon_id'] == melon_id:
                    mel['quantity'] += int(form.quantity.data)
                    mel['subtotal'] = mel['price'] * mel['quantity']
                    print(f'melon in session{mel}') 
                    melon_update = mel
                    print(f'melon update {melon_update}')
                    session.modified = True
                    flash(f'{melon.common_name} has been updated!')
                    break 

            if melon_update is None:
                new_melon = Melon.to_dict(melon)
                new_melon['quantity'] = int(form.quantity.data)
                new_melon['subtotal'] = new_melon['price'] * new_melon['quantity']
                print(f'melon {new_melon}') 
                session['cart'].append(new_melon)
                session.modified = True
                flash(f'{melon.common_name} has been added to cart!')
                print(f"session cart {session['cart']}")   
            return redirect(url_for('cart.view_cart'))
        
    return render_template('melon_details.html', melon=melon, form=form)

melonStore/project/melons/templates/melons/all_melons.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron container-fluid row flex" >
        <h1>Melons Gallery</h1>
        <p>Click the melon to view details</p>
        <div class="row">
            {% for melon in melons %}
                <div class="col-md-2 mb-4">
                    <a href="{{ url_for('melons.melon_details', melon_id=melon.melon_id) }}">        
                        <img src="{{ melon.display_img() }}" alt="{{ melon.common_name }}" class="rounded galleryImg" >
                    </a>
                    <br>
                    {{ melon.all_melon_display() }}
                </div>
                {% endfor %}
        </div>

    </div>
{% endblock %}

melonStore/project/melons/templates/melons/melon_details.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron container-fluid row flex" >
        <h1>Melon Details</h1>
        {% if melon %}
        <div class="row">
            <div class="col-md-5">
                <img class="img-thumbnail" src="{{ melon.image_url }}" alt="{{ melon.common_name }}" style="width: 100%;">
            </div>
            <div class="col-md-5">
                <h4>
                    Name: {{melon.common_name}} <br>
                    Price: ${{melon.price}}<br>
                    Color: {{melon.color}}<br>
                    Seedless: {{melon.seedless}}
                </h4>
                <div class="col-md-6">
                    <form action="/melons/melon_details/{{melon.melon_id}}" method="post">
                        <ul class="list-group">
                            {{form.hidden_tag()}}
                            <li class="list-group-item">
                                {{form.quantity.label}} {{form.quantity()}}
                            </li>
                            <li class="list-group-item">
                                {{form.submit()}}
                            </li>
                        </ul>
                    </form>
                </div>
        </div>
        {% endif %}
    </div>
{% endblock %}